## Deliverable 2. Create a Customer Travel Destinations Map.

In [5]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [6]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Saint-Philippe,RE,-21.3585,55.7679,81.99,84,61,9.71,light rain
1,1,Hithadhoo,MV,-0.6000,73.0833,81.48,66,100,5.28,overcast clouds
2,2,Ponta Do Sol,PT,32.6667,-17.1000,71.71,52,94,7.23,overcast clouds
3,3,Aanekoski,FI,62.6946,25.8180,28.47,100,100,14.54,light snow
4,4,Arman,RU,59.7000,150.1667,7.03,82,82,13.67,broken clouds

In [7]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [9]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Saint-Philippe,RE,-21.3585,55.7679,81.99,84,61,9.71,light rain
1,1,Hithadhoo,MV,-0.6000,73.0833,81.48,66,100,5.28,overcast clouds
8,8,Port-Gentil,GA,-0.7193,8.7815,85.96,74,40,11.50,light rain
11,11,Mar Del Plata,AR,-38.0023,-57.5575,77.02,55,0,8.99,clear sky
17,17,Punta Alta,AR,-38.8759,-62.0736,86.77,32,0,24.16,clear sky
20,20,Kasongo-Lunda,CD,-6.4667,16.8167,85.08,57,95,4.76,overcast clouds
22,22,Rikitea,PF,-23.1203,-134.9692,77.07,76,85,11.95,overcast clouds
23,23,Katobu,ID,-4.9408,122.5276,76.73,85,100,1.41,overcast clouds
26,26,Vila Velha,BR,-20.3297,-40.2925,89.55,61,0,14.00,clear sky
28,28,Grand-Lahou,CI,5.1367,-5.0242,86.65,63,55,11.95,broken clouds

In [10]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                227
City                   227
Country                226
Lat                    227
Lng                    227
Max Temp               227
Humidity               227
Cloudiness             227
Wind Speed             227
Current Description    227
dtype: int64

In [11]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)].dropna()
clean_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Saint-Philippe,RE,-21.3585,55.7679,81.99,84,61,9.71,light rain
1,1,Hithadhoo,MV,-0.6000,73.0833,81.48,66,100,5.28,overcast clouds
8,8,Port-Gentil,GA,-0.7193,8.7815,85.96,74,40,11.50,light rain
11,11,Mar Del Plata,AR,-38.0023,-57.5575,77.02,55,0,8.99,clear sky
17,17,Punta Alta,AR,-38.8759,-62.0736,86.77,32,0,24.16,clear sky
20,20,Kasongo-Lunda,CD,-6.4667,16.8167,85.08,57,95,4.76,overcast clouds
22,22,Rikitea,PF,-23.1203,-134.9692,77.07,76,85,11.95,overcast clouds
23,23,Katobu,ID,-4.9408,122.5276,76.73,85,100,1.41,overcast clouds
26,26,Vila Velha,BR,-20.3297,-40.2925,89.55,61,0,14.00,clear sky
28,28,Grand-Lahou,CI,5.1367,-5.0242,86.65,63,55,11.95,broken clouds

In [12]:
clean_df.count()

City_ID                226
City                   226
Country                226
Lat                    226
Lng                    226
Max Temp               226
Humidity               226
Cloudiness             226
Wind Speed             226
Current Description    226
dtype: int64

In [13]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Saint-Philippe,RE,81.99,light rain,-21.3585,55.7679,
1,Hithadhoo,MV,81.48,overcast clouds,-0.6000,73.0833,
8,Port-Gentil,GA,85.96,light rain,-0.7193,8.7815,
11,Mar Del Plata,AR,77.02,clear sky,-38.0023,-57.5575,
17,Punta Alta,AR,86.77,clear sky,-38.8759,-62.0736,
20,Kasongo-Lunda,CD,85.08,overcast clouds,-6.4667,16.8167,
22,Rikitea,PF,77.07,overcast clouds,-23.1203,-134.9692,
23,Katobu,ID,76.73,overcast clouds,-4.9408,122.5276,
26,Vila Velha,BR,89.55,clear sky,-20.3297,-40.2925,
28,Grand-Lahou,CI,86.65,broken clouds,5.1367,-5.0242,

In [16]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [17]:
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Saint-Philippe,RE,81.99,light rain,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
1,Hithadhoo,MV,81.48,overcast clouds,-0.6000,73.0833,Scoop Guest House
8,Port-Gentil,GA,85.96,light rain,-0.7193,8.7815,Fengshui Residence
11,Mar Del Plata,AR,77.02,clear sky,-38.0023,-57.5575,Gran Hotel Mar del Plata
17,Punta Alta,AR,86.77,clear sky,-38.8759,-62.0736,Center Hotel Punta Alta
20,Kasongo-Lunda,CD,85.08,overcast clouds,-6.4667,16.8167,
22,Rikitea,PF,77.07,overcast clouds,-23.1203,-134.9692,People ThankYou
23,Katobu,ID,76.73,overcast clouds,-4.9408,122.5276,La Ode Husein
26,Vila Velha,BR,89.55,clear sky,-20.3297,-40.2925,Quality Suites Vila Velha
28,Grand-Lahou,CI,86.65,broken clouds,5.1367,-5.0242,Hotel Beatitude de Grand Lahou

In [18]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Saint-Philippe,RE,81.99,light rain,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
1,Hithadhoo,MV,81.48,overcast clouds,-0.6000,73.0833,Scoop Guest House
8,Port-Gentil,GA,85.96,light rain,-0.7193,8.7815,Fengshui Residence
11,Mar Del Plata,AR,77.02,clear sky,-38.0023,-57.5575,Gran Hotel Mar del Plata
17,Punta Alta,AR,86.77,clear sky,-38.8759,-62.0736,Center Hotel Punta Alta
...,...,...,...,...,...,...,...
675,Sao Desiderio,BR,78.48,overcast clouds,-12.3633,-44.9733,Hotel azaf
677,Gao,ML,84.94,few clouds,16.6362,1.6370,
678,Minas,UY,77.47,clear sky,-34.3759,-55.2377,Hotel Minas
679,Kampong Chhnang,KH,81.57,broken clouds,12.1667,104.5500,ផ្ទះសំណាក់ហេងស្រស់
683,Mildura,AU,75.16,clear sky,-34.2000,142.1500,Mercure Hotel Mildura

In [20]:
# 8a. Create the output File (CSV)
output_data_file = "../Vacation_Search/WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [22]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
<dt>Current Description</dt><dd>{Current Description}<dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [23]:
# 11a. Add a marker layer for each city to the map. 
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))